using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TabulariusAI.Web.Data;
using TabulariusAI.Web.Data.Entities;
using TabulariusAI.Web.Models;
using TabulariusAI.Web.Services;

namespace TabulariusAI.Web.Controllers;

public sealed class DossierController(TabulariusDbContext dbContext) : Controller
{
    private static readonly int[] AllowedPageSizes = [10,25,50,100];
    public async Task<IActionResult> Entities(string? search,int page=1,int pageSize=10,CancellationToken cancellationToken=default){var q=dbContext.AccountingEntities.AsNoTracking().Include(x=>x.Dossiers).AsQueryable();if(!string.IsNullOrWhiteSpace(search)){var t=search.Trim();q=q.Where(x=>x.Name.Contains(t)||x.TaxRegistrationNumber.Contains(t));}return View(await PageAsync(q.OrderBy(x=>x.Name),search,page,pageSize,cancellationToken));}
    public async Task<IActionResult> Entity(int id,string? search,int page=1,int pageSize=10,CancellationToken cancellationToken=default){var entity=await dbContext.AccountingEntities.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,cancellationToken);if(entity is null)return NotFound();var q=dbContext.AnalysisDossiers.AsNoTracking().Include(x=>x.Imports).Where(x=>x.AccountingEntityId==id);if(!string.IsNullOrWhiteSpace(search)){var t=search.Trim();q=q.Where(x=>x.Name.Contains(t)||x.FiscalYear.ToString().Contains(t));}return View(new EntityDossiersViewModel{Entity=entity,List=await PageAsync(q.OrderByDescending(x=>x.FiscalYear).ThenBy(x=>x.Name),search,page,pageSize,cancellationToken)});}
    public async Task<IActionResult> Details(int id,CancellationToken cancellationToken){var d=await LoadDossierAsync(id,cancellationToken);return d is null?NotFound():View(d);}
    [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> DeleteEntity(int id,CancellationToken cancellationToken){var x=await dbContext.AccountingEntities.SingleOrDefaultAsync(i=>i.Id==id,cancellationToken);if(x is null)return NotFound();dbContext.AccountingEntities.Remove(x);await dbContext.SaveChangesAsync(cancellationToken);return RedirectToAction(nameof(Entities));}
    [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> DeleteDossier(int id,CancellationToken cancellationToken){var x=await dbContext.AnalysisDossiers.SingleOrDefaultAsync(i=>i.Id==id,cancellationToken);if(x is null)return NotFound();var e=x.AccountingEntityId;dbContext.AnalysisDossiers.Remove(x);await dbContext.SaveChangesAsync(cancellationToken);return RedirectToAction(nameof(Entity),new{id=e});}
    [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> DeleteImport(int id,CancellationToken cancellationToken){var x=await dbContext.SaftImports.SingleOrDefaultAsync(i=>i.Id==id,cancellationToken);if(x is null)return NotFound();var d=x.DossierId;dbContext.SaftImports.Remove(x);await dbContext.SaveChangesAsync(cancellationToken);return RedirectToAction(nameof(Details),new{id=d});}
    public async Task<IActionResult> SaftSummary(int id,int? importId,CancellationToken cancellationToken)=>await ImportViewAsync(id,importId,cancellationToken,q=>q.Include(x=>x.Accounts).Include(x=>x.Customers).Include(x=>x.Suppliers).Include(x=>x.Products));
    public async Task<IActionResult> Accounts(int id,int? importId,string? search,int page=1,int pageSize=10,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var q=dbContext.SaftAccounts.AsNoTracking().Where(x=>x.SaftImportId==s.SelectedImport.Id);if(!string.IsNullOrWhiteSpace(search)){var t=search.Trim();q=q.Where(x=>x.AccountId.Contains(t)||x.Description.Contains(t));}return View(new SaftListViewModel<SaftAccount>{Source=s,List=await PageAsync(q.OrderBy(x=>x.AccountId),search,page,pageSize,cancellationToken)});}
    public async Task<IActionResult> Customers(int id,int? importId,string? search,int page=1,int pageSize=10,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var q=dbContext.SaftCustomers.AsNoTracking().Where(x=>x.SaftImportId==s.SelectedImport.Id);if(!string.IsNullOrWhiteSpace(search)){var t=search.Trim();q=q.Where(x=>x.CustomerId.Contains(t)||x.CompanyName.Contains(t)||x.TaxId.Contains(t));}return View(new SaftListViewModel<SaftCustomer>{Source=s,List=await PageAsync(q.OrderBy(x=>x.CompanyName),search,page,pageSize,cancellationToken)});}
    public async Task<IActionResult> Suppliers(int id,int? importId,string? search,int page=1,int pageSize=10,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var q=dbContext.SaftSuppliers.AsNoTracking().Where(x=>x.SaftImportId==s.SelectedImport.Id);if(!string.IsNullOrWhiteSpace(search)){var t=search.Trim();q=q.Where(x=>x.SupplierId.Contains(t)||x.CompanyName.Contains(t)||x.TaxId.Contains(t));}return View(new SaftListViewModel<SaftSupplier>{Source=s,List=await PageAsync(q.OrderBy(x=>x.CompanyName),search,page,pageSize,cancellationToken)});}
    public async Task<IActionResult> Products(int id,int? importId,string? search,int page=1,int pageSize=10,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var q=dbContext.SaftProducts.AsNoTracking().Where(x=>x.SaftImportId==s.SelectedImport.Id);if(!string.IsNullOrWhiteSpace(search)){var t=search.Trim();q=q.Where(x=>x.ProductCode.Contains(t)||x.ProductDescription.Contains(t));}return View(new SaftListViewModel<SaftProduct>{Source=s,List=await PageAsync(q.OrderBy(x=>x.ProductDescription),search,page,pageSize,cancellationToken)});}
    public async Task<IActionResult> AccountingEntries(int id,int? importId,string? search,int page=1,int pageSize=10,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var q=dbContext.SaftTransactions.AsNoTracking().Where(x=>x.SaftImportId==s.SelectedImport.Id);if(!string.IsNullOrWhiteSpace(search)){var t=search.Trim();q=q.Where(x=>x.TransactionId.Contains(t)||x.Description.Contains(t)||x.JournalId.Contains(t));}return View(new SaftListViewModel<SaftTransaction>{Source=s,List=await PageAsync(q.OrderByDescending(x=>x.TransactionDate),search,page,pageSize,cancellationToken)});}
    public async Task<IActionResult> AccountingEntry(int id,int importId,int transactionId,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var t=await dbContext.SaftTransactions.AsNoTracking().Include(x=>x.Lines).SingleOrDefaultAsync(x=>x.Id==transactionId&&x.SaftImportId==s.SelectedImport.Id,cancellationToken);return t is null?NotFound():View(new SaftEntryDetailViewModel{Source=s,Transaction=t});}
    public async Task<IActionResult> TrialBalance(int id,int? importId,string? search,bool includeZeroAccounts=false,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var a=await dbContext.SaftAccounts.AsNoTracking().Where(x=>x.SaftImportId==s.SelectedImport.Id).ToListAsync(cancellationToken);var l=await dbContext.SaftTransactionLines.AsNoTracking().Where(x=>x.SaftTransaction.SaftImportId==s.SelectedImport.Id).ToListAsync(cancellationToken);var rows=TrialBalanceCalculator.Calculate(a,l).AsEnumerable();if(!includeZeroAccounts)rows=rows.Where(x=>x.OpeningDebit!=0||x.OpeningCredit!=0||x.DebitMovements!=0||x.CreditMovements!=0||x.ReportedClosingDebit!=0||x.ReportedClosingCredit!=0);var t=search?.Trim();if(!string.IsNullOrWhiteSpace(t))rows=rows.Where(x=>x.AccountId.Contains(t,StringComparison.OrdinalIgnoreCase)||x.Description.Contains(t,StringComparison.OrdinalIgnoreCase));return View(new TrialBalanceViewModel{Source=s,Rows=rows.ToList(),Search=t,IncludeZeroAccounts=includeZeroAccounts});}
    public async Task<IActionResult> IncomeStatement(int id,int? importId,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var a=await dbContext.SaftAccounts.AsNoTracking().Where(x=>x.SaftImportId==s.SelectedImport.Id).ToListAsync(cancellationToken);var l=await dbContext.SaftTransactionLines.AsNoTracking().Where(x=>x.SaftTransaction.SaftImportId==s.SelectedImport.Id).ToListAsync(cancellationToken);var m=IncomeStatementCalculator.Calculate(a,l);m.Source=s;return View(m);}
    public async Task<IActionResult> BalanceSheet(int id,int? importId,CancellationToken cancellationToken=default){var s=await LoadSourceAsync(id,importId,cancellationToken);if(s is null)return NotFound();var a=await dbContext.SaftAccounts.AsNoTracking().Where(x=>x.SaftImportId==s.SelectedImport.Id).ToListAsync(cancellationToken);var m=BalanceSheetCalculator.Calculate(a);m.Source=s;return View(m);}
    private async Task<IActionResult> ImportViewAsync(int id,int? importId,CancellationToken ct,Func<IQueryable<SaftImport>,IQueryable<SaftImport>> include){var s=await LoadSourceAsync(id,importId,ct,include);return s is null?NotFound():View(s);}
    private async Task<SaftImportSelectionViewModel?> LoadSourceAsync(int id,int? importId,CancellationToken ct,Func<IQueryable<SaftImport>,IQueryable<SaftImport>>? include=null){var all=await dbContext.SaftImports.AsNoTracking().Where(x=>x.DossierId==id).OrderByDescending(x=>x.EndDate).ThenByDescending(x=>x.ImportedAtUtc).ToListAsync(ct);if(all.Count==0)return null;var selected=importId??all[0].Id;if(!all.Any(x=>x.Id==selected))return null;IQueryable<SaftImport> q=dbContext.SaftImports.AsNoTracking().Include(x=>x.Dossier).ThenInclude(x=>x.AccountingEntity);if(include is not null)q=include(q);var i=await q.SingleOrDefaultAsync(x=>x.Id==selected&&x.DossierId==id,ct);return i is null?null:new SaftImportSelectionViewModel{SelectedImport=i,AvailableImports=all};}
    private static async Task<PagedListViewModel<T>> PageAsync<T>(IQueryable<T> q,string? search,int page,int pageSize,CancellationToken ct){pageSize=AllowedPageSizes.Contains(pageSize)?pageSize:10;page=Math.Max(1,page);var total=await q.CountAsync(ct);var pages=Math.Max(1,(int)Math.Ceiling(total/(double)pageSize));page=Math.Min(page,pages);return new PagedListViewModel<T>{Items=await q.Skip((page-1)*pageSize).Take(pageSize).ToListAsync(ct),TotalItems=total,Page=page,PageSize=pageSize,Search=search?.Trim()};}
    private async Task<AnalysisDossier?> LoadDossierAsync(int id,CancellationToken ct)=>await dbContext.AnalysisDossiers.AsNoTracking().Include(x=>x.AccountingEntity).Include(x=>x.Imports).SingleOrDefaultAsync(x=>x.Id==id,ct);
}
