using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TabulariusAI.Web.Data;
using TabulariusAI.Web.Data.Entities;
using TabulariusAI.Web.Models;
using TabulariusAI.Web.Services;
namespace TabulariusAI.Web.Controllers;
public sealed class HomeController(ISaftHeaderReader saftHeaderReader,TabulariusDbContext dbContext):Controller
{
 private const long MaximumSaftFileSize=100*1024*1024;public IActionResult Index()=>View();[HttpGet]public IActionResult Import()=>View();
 [HttpPost,ValidateAntiForgeryToken,RequestFormLimits(MultipartBodyLengthLimit=MaximumSaftFileSize),RequestSizeLimit(MaximumSaftFileSize)]public async Task<IActionResult> UploadSaftAsync(IFormFile? saftFile,CancellationToken ct){if(saftFile is null||saftFile.Length==0){ModelState.AddModelError("saftFile","Selecione um ficheiro SAF-T (PT) em formato XML.");return View("Import");}if(saftFile.Length>MaximumSaftFileSize){ModelState.AddModelError("saftFile","O ficheiro SAF-T (PT) não pode exceder 100 MB.");return View("Import");}if(!string.Equals(Path.GetExtension(saftFile.FileName),".xml",StringComparison.OrdinalIgnoreCase)){ModelState.AddModelError("saftFile","O ficheiro selecionado deve ter a extensão .xml.");return View("Import");}try{var hash=await CalculateContentHashAsync(saftFile,ct);if(await dbContext.SaftImports.AsNoTracking().AnyAsync(x=>x.ContentHash==hash,ct)){ModelState.AddModelError("saftFile","Este ficheiro SAF-T (PT) já foi importado. Selecione um ficheiro diferente.");return View("Import");}await using var stream=saftFile.OpenReadStream();var analysis=await saftHeaderReader.ReadAsync(stream,ct);await PersistImportAsync(saftFile.FileName,hash,analysis,ct);TempData["SaftImportValidation"]="Ficheiro SAF-T (PT) analisado e importado com sucesso.";return View("Import",analysis);}catch(InvalidDataException ex){ModelState.AddModelError("saftFile",ex.Message);return View("Import");}catch(DbUpdateException){ModelState.AddModelError("saftFile","O ficheiro foi analisado, mas não foi possível guardar os dados do dossier localmente.");return View("Import");}}
 [ResponseCache(Duration=0,Location=ResponseCacheLocation.None,NoStore=true)]public IActionResult Error()=>View(new ErrorViewModel{RequestId=Activity.Current?.Id??HttpContext.TraceIdentifier});private static async Task<string> CalculateContentHashAsync(IFormFile f,CancellationToken ct){await using var s=f.OpenReadStream();return Convert.ToHexStringLower(await SHA256.HashDataAsync(s,ct));}
 private async Task PersistImportAsync(string fileName,string hash,SaftHeaderViewModel a,CancellationToken ct){await using var tx=await dbContext.Database.BeginTransactionAsync(ct);var entity=await dbContext.AccountingEntities.SingleOrDefaultAsync(x=>x.TaxRegistrationNumber==a.TaxRegistrationNumber,ct);if(entity is null){entity=new AccountingEntity{Name=a.CompanyName,TaxRegistrationNumber=a.TaxRegistrationNumber};dbContext.AccountingEntities.Add(entity);await dbContext.SaveChangesAsync(ct);}else entity.Name=a.CompanyName;if(!int.TryParse(a.FiscalYear,NumberStyles.None,CultureInfo.InvariantCulture,out var year)||year<=0)throw new InvalidDataException("O SAF-T (PT) não contém um exercício fiscal válido.");var dossier=await dbContext.AnalysisDossiers.SingleOrDefaultAsync(x=>x.AccountingEntityId==entity.Id&&x.FiscalYear==year,ct);if(dossier is null){dossier=new AnalysisDossier{AccountingEntityId=entity.Id,FiscalYear=year,Name=$"Exercício {year}"};dbContext.AnalysisDossiers.Add(dossier);}var import=new SaftImport{OriginalFileName=Path.GetFileName(fileName),ContentHash=hash,SaftVersion=a.SaftVersion,StartDate=ParseDate(a.StartDate),EndDate=ParseDate(a.EndDate)};
 foreach(var x in a.Accounts)import.Accounts.Add(new(){AccountId=x.AccountId,Description=x.Description,OpeningDebitBalance=x.OpeningDebitBalance,OpeningCreditBalance=x.OpeningCreditBalance,ClosingDebitBalance=x.ClosingDebitBalance,ClosingCreditBalance=x.ClosingCreditBalance,TaxonomyReference=x.TaxonomyReference});foreach(var x in a.Customers)import.Customers.Add(new(){CustomerId=x.PartyId,AccountId=x.AccountId,TaxId=x.TaxId,CompanyName=x.CompanyName});foreach(var x in a.Suppliers)import.Suppliers.Add(new(){SupplierId=x.PartyId,AccountId=x.AccountId,TaxId=x.TaxId,CompanyName=x.CompanyName});foreach(var x in a.Products)import.Products.Add(new(){ProductType=x.ProductType,ProductCode=x.ProductCode,ProductGroup=x.ProductGroup,ProductDescription=x.ProductDescription,ProductNumberCode=x.ProductNumberCode});foreach(var x in a.TaxEntries)import.TaxEntries.Add(new(){TaxType=x.TaxType,TaxCountryRegion=x.TaxCountryRegion,TaxCode=x.TaxCode,Description=x.Description,TaxExpirationDate=x.TaxExpirationDate,TaxPercentage=x.TaxPercentage,TaxAmount=x.TaxAmount});
 foreach(var x in a.Transactions){var d=new SaftTransaction{JournalId=x.JournalId,JournalDescription=x.JournalDescription,TransactionId=x.TransactionId,Period=x.Period,TransactionDate=x.TransactionDate,SourceId=x.SourceId,Description=x.Description,DocArchivalNumber=x.DocArchivalNumber,TransactionType=x.TransactionType,GlPostingDate=x.GlPostingDate,CustomerId=x.CustomerId,SupplierId=x.SupplierId};foreach(var l in x.Lines)d.Lines.Add(new(){RecordId=l.RecordId,AccountId=l.AccountId,SourceDocumentId=l.SourceDocumentId,SystemEntryDate=l.SystemEntryDate,Description=l.Description,Side=l.Side,Amount=l.Amount});import.Transactions.Add(d);}foreach(var x in a.SalesInvoices){var d=new SaftSalesInvoice{InvoiceNo=x.InvoiceNo,InvoiceStatus=x.InvoiceStatus,InvoiceDate=x.InvoiceDate,InvoiceType=x.InvoiceType,SourceId=x.SourceId,CustomerId=x.CustomerId,SystemEntryDate=x.SystemEntryDate,TaxPayable=x.TaxPayable,NetTotal=x.NetTotal,GrossTotal=x.GrossTotal};foreach(var l in x.Lines)d.Lines.Add(new(){LineNumber=l.LineNumber,ProductCode=l.ProductCode,ProductDescription=l.ProductDescription,Quantity=l.Quantity,UnitOfMeasure=l.UnitOfMeasure,UnitPrice=l.UnitPrice,TaxPointDate=l.TaxPointDate,TaxType=l.TaxType,TaxCode=l.TaxCode,TaxPercentage=l.TaxPercentage,DebitAmount=l.DebitAmount,CreditAmount=l.CreditAmount});import.SalesInvoices.Add(d);}foreach(var x in a.StockMovements){var d=new SaftStockMovement{DocumentNumber=x.DocumentNumber,DocumentStatus=x.DocumentStatus,MovementDate=x.MovementDate,MovementType=x.MovementType,SourceId=x.SourceId,CustomerId=x.CustomerId,SupplierId=x.SupplierId,SystemEntryDate=x.SystemEntryDate};foreach(var l in x.Lines)d.Lines.Add(new(){LineNumber=l.LineNumber,ProductCode=l.ProductCode,ProductDescription=l.ProductDescription,Quantity=l.Quantity,UnitOfMeasure=l.UnitOfMeasure,UnitPrice=l.UnitPrice});import.StockMovements.Add(d);}
 foreach(var x in a.WorkingDocuments){var d=new SaftWorkingDocument{DocumentNumber=x.DocumentNumber,DocumentStatus=x.DocumentStatus,WorkDate=x.WorkDate,WorkType=x.WorkType,SourceId=x.SourceId,CustomerId=x.CustomerId,SystemEntryDate=x.SystemEntryDate,TaxPayable=x.TaxPayable,NetTotal=x.NetTotal,GrossTotal=x.GrossTotal};foreach(var l in x.Lines)d.Lines.Add(new(){LineNumber=l.LineNumber,ProductCode=l.ProductCode,ProductDescription=l.ProductDescription,Quantity=l.Quantity,UnitOfMeasure=l.UnitOfMeasure,UnitPrice=l.UnitPrice,TaxPointDate=l.TaxPointDate,TaxType=l.TaxType,TaxCode=l.TaxCode,TaxPercentage=l.TaxPercentage,DebitAmount=l.DebitAmount,CreditAmount=l.CreditAmount});import.WorkingDocuments.Add(d);}foreach(var x in a.Payments){var d=new SaftPayment{PaymentRefNo=x.PaymentRefNo,TransactionDate=x.TransactionDate,PaymentType=x.PaymentType,Description=x.Description,SourceId=x.SourceId,CustomerId=x.CustomerId,SystemEntryDate=x.SystemEntryDate,PaymentStatus=x.PaymentStatus,TaxPayable=x.TaxPayable,NetTotal=x.NetTotal,GrossTotal=x.GrossTotal};foreach(var l in x.Lines)d.Lines.Add(new(){LineNumber=l.LineNumber,OriginatingOn=l.OriginatingOn,InvoiceDate=l.InvoiceDate,Description=l.Description,DebitAmount=l.DebitAmount,CreditAmount=l.CreditAmount});import.Payments.Add(d);}dossier.Imports.Add(import);await dbContext.SaveChangesAsync(ct);await tx.CommitAsync(ct);}
 private static DateOnly? ParseDate(string v)=>DateOnly.TryParseExact(v,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var d)?d:null;
}
