using System.Globalization;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using TabulariusAI.Web.Models;

namespace TabulariusAI.Web.Services;

public sealed class SaftHeaderReader : ISaftHeaderReader
{
    static SaftHeaderReader()=>Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
    public async Task<SaftHeaderViewModel> ReadAsync(Stream stream,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(stream);var settings=new XmlReaderSettings{Async=true,DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null,IgnoreComments=true,IgnoreWhitespace=true,CloseInput=false};
        try{using var reader=XmlReader.Create(stream,settings);var model=new SaftHeaderViewModel();var rootValidated=false;var advance=true;while(true){if(advance&&!await reader.ReadAsync())break;advance=true;cancellationToken.ThrowIfCancellationRequested();if(reader.NodeType!=XmlNodeType.Element)continue;if(!rootValidated){ValidateRoot(reader);rootValidated=true;continue;}switch(reader.LocalName){case "Header":await ParseElementAsync(reader,cancellationToken,e=>ParseHeader(e,model));advance=false;break;case "MasterFiles":await ParseElementAsync(reader,cancellationToken,e=>ParseMasterFiles(e,model));advance=false;break;case "Journal":await ParseElementAsync(reader,cancellationToken,e=>ParseJournal(e,model));advance=false;break;case "Invoice":await ParseElementAsync(reader,cancellationToken,e=>model.SalesInvoices.Add(ParseSalesInvoice(e)));advance=false;break;case "StockMovement":await ParseElementAsync(reader,cancellationToken,e=>model.StockMovements.Add(ParseStockMovement(e)));advance=false;break;case "WorkDocument":await ParseElementAsync(reader,cancellationToken,e=>model.WorkingDocuments.Add(ParseWorkingDocument(e)));advance=false;break;case "Payment":await ParseElementAsync(reader,cancellationToken,e=>model.Payments.Add(ParsePayment(e)));advance=false;break;}}model.TransactionCount=model.Transactions.Count;model.SalesInvoiceCount=model.SalesInvoices.Count;model.MovementOfGoodsCount=model.StockMovements.Count;model.WorkingDocumentCount=model.WorkingDocuments.Count;model.PaymentCount=model.Payments.Count;ValidateRequiredHeader(model);return model;}catch(XmlException ex){throw new InvalidDataException($"Não foi possível ler o XML SAF-T (PT): {ex.Message}",ex);}
    }
    private static async Task ParseElementAsync(XmlReader reader,CancellationToken ct,Action<XElement> map){var node=await XNode.ReadFromAsync(reader,ct);if(node is XElement e)map(e);}
    private static void ValidateRoot(XmlReader r){if(!string.Equals(r.LocalName,"AuditFile",StringComparison.Ordinal)||!r.NamespaceURI.StartsWith("urn:OECD:StandardAuditFile-Tax:PT_",StringComparison.Ordinal))throw new InvalidDataException("O ficheiro XML não contém uma estrutura SAF-T (PT) reconhecida.");}
    private static void ParseHeader(XElement e,SaftHeaderViewModel m){var n=e.Name.Namespace;m.SaftVersion=Opt(e,n+"AuditFileVersion");m.TaxRegistrationNumber=Opt(e,n+"TaxRegistrationNumber");m.CompanyName=Opt(e,n+"CompanyName");m.FiscalYear=Opt(e,n+"FiscalYear");m.StartDate=Opt(e,n+"StartDate");m.EndDate=Opt(e,n+"EndDate");m.ProductId=Opt(e,n+"ProductID");m.ProductVersion=Opt(e,n+"ProductVersion");}
    private static void ParseMasterFiles(XElement e,SaftHeaderViewModel m){var n=e.Name.Namespace;var accounts=e.Element(n+"GeneralLedgerAccounts");if(accounts!=null)foreach(var x in accounts.Elements(n+"Account"))m.Accounts.Add(ParseAccount(x));foreach(var x in e.Elements(n+"Customer"))m.Customers.Add(ParseParty(x,"CustomerID","CustomerTaxID"));foreach(var x in e.Elements(n+"Supplier"))m.Suppliers.Add(ParseParty(x,"SupplierID","SupplierTaxID"));foreach(var x in e.Elements(n+"Product"))m.Products.Add(ParseProduct(x));var taxes=e.Element(n+"TaxTable");if(taxes!=null)foreach(var x in taxes.Elements(n+"TaxTableEntry"))m.TaxEntries.Add(ParseTaxEntry(x));m.AccountCount=m.Accounts.Count;m.CustomerCount=m.Customers.Count;m.SupplierCount=m.Suppliers.Count;m.ProductCount=m.Products.Count;m.TaxEntryCount=m.TaxEntries.Count;}
    private static void ParseJournal(XElement e,SaftHeaderViewModel m){var n=e.Name.Namespace;var id=Req(e,n+"JournalID");var d=Req(e,n+"Description");foreach(var x in e.Elements(n+"Transaction"))m.Transactions.Add(ParseTransaction(x,id,d));}
    private static SaftTransactionViewModel ParseTransaction(XElement e,string journal,string journalDescription){var n=e.Name.Namespace;var r=new SaftTransactionViewModel{JournalId=journal,JournalDescription=journalDescription,TransactionId=Req(e,n+"TransactionID"),Period=Int(e,n+"Period"),TransactionDate=Date(e,n+"TransactionDate"),SourceId=Req(e,n+"SourceID"),Description=Req(e,n+"Description"),DocArchivalNumber=e.Element(n+"DocArchivalNumber")?.Value,TransactionType=Req(e,n+"TransactionType"),GlPostingDate=Date(e,n+"GLPostingDate"),CustomerId=e.Element(n+"CustomerID")?.Value,SupplierId=e.Element(n+"SupplierID")?.Value};var lines=e.Element(n+"Lines")??throw new InvalidDataException("O SAF-T (PT) contém uma transação contabilística sem Lines.");foreach(var x in lines.Elements(n+"DebitLine"))r.Lines.Add(ParseTransactionLine(x,"D",n+"DebitAmount"));foreach(var x in lines.Elements(n+"CreditLine"))r.Lines.Add(ParseTransactionLine(x,"C",n+"CreditAmount"));return r;}
    private static SaftTransactionLineViewModel ParseTransactionLine(XElement e,string side,XName amount){var n=e.Name.Namespace;return new(){RecordId=Req(e,n+"RecordID"),AccountId=Req(e,n+"AccountID"),SourceDocumentId=e.Element(n+"SourceDocumentID")?.Value,SystemEntryDate=OptionalDateTime(e,n+"SystemEntryDate"),Description=Req(e,n+"Description"),Side=side,Amount=Decimal(e,amount)};}
    private static SaftSalesInvoiceViewModel ParseSalesInvoice(XElement e){var n=e.Name.Namespace;var s=e.Element(n+"DocumentStatus");var t=e.Element(n+"DocumentTotals")??throw new InvalidDataException("O SAF-T (PT) contém uma fatura sem DocumentTotals.");var r=new SaftSalesInvoiceViewModel{InvoiceNo=Req(e,n+"InvoiceNo"),InvoiceStatus=s?.Element(n+"InvoiceStatus")?.Value??string.Empty,InvoiceDate=Date(e,n+"InvoiceDate"),InvoiceType=Req(e,n+"InvoiceType"),SourceId=Req(e,n+"SourceID"),CustomerId=e.Element(n+"CustomerID")?.Value,SystemEntryDate=OptionalDateTime(e,n+"SystemEntryDate"),TaxPayable=Decimal(t,n+"TaxPayable"),NetTotal=Decimal(t,n+"NetTotal"),GrossTotal=Decimal(t,n+"GrossTotal")};foreach(var x in e.Elements(n+"Line"))r.Lines.Add(ParseSalesLine(x));return r;}
    private static SaftSalesInvoiceLineViewModel ParseSalesLine(XElement e){var n=e.Name.Namespace;var tax=e.Element(n+"Tax");return new(){LineNumber=Req(e,n+"LineNumber"),ProductCode=Req(e,n+"ProductCode"),ProductDescription=Req(e,n+"ProductDescription"),Quantity=Decimal(e,n+"Quantity"),UnitOfMeasure=Req(e,n+"UnitOfMeasure"),UnitPrice=Decimal(e,n+"UnitPrice"),TaxPointDate=OptionalDate(e,n+"TaxPointDate"),TaxType=tax?.Element(n+"TaxType")?.Value,TaxCode=tax?.Element(n+"TaxCode")?.Value,TaxPercentage=OptionalDecimal(tax,n+"TaxPercentage"),DebitAmount=OptionalDecimal(e,n+"DebitAmount")??0m,CreditAmount=OptionalDecimal(e,n+"CreditAmount")??0m};}
    private static SaftStockMovementViewModel ParseStockMovement(XElement e){var n=e.Name.Namespace;var s=e.Element(n+"DocumentStatus");var r=new SaftStockMovementViewModel{DocumentNumber=Req(e,n+"DocumentNumber"),DocumentStatus=s?.Element(n+"MovementStatus")?.Value??string.Empty,MovementDate=Date(e,n+"MovementDate"),MovementType=Req(e,n+"MovementType"),SourceId=Req(e,n+"SourceID"),CustomerId=e.Element(n+"CustomerID")?.Value,SupplierId=e.Element(n+"SupplierID")?.Value,SystemEntryDate=OptionalDateTime(e,n+"SystemEntryDate")};foreach(var x in e.Elements(n+"Line"))r.Lines.Add(new(){LineNumber=Req(x,n+"LineNumber"),ProductCode=Req(x,n+"ProductCode"),ProductDescription=Req(x,n+"ProductDescription"),Quantity=Decimal(x,n+"Quantity"),UnitOfMeasure=Req(x,n+"UnitOfMeasure"),UnitPrice=OptionalDecimal(x,n+"UnitPrice")});return r;}
    private static SaftWorkingDocumentViewModel ParseWorkingDocument(XElement e){var n=e.Name.Namespace;var s=e.Element(n+"DocumentStatus");var t=e.Element(n+"DocumentTotals")??throw new InvalidDataException("O SAF-T (PT) contém um documento de conferência sem DocumentTotals.");var r=new SaftWorkingDocumentViewModel{DocumentNumber=Req(e,n+"DocumentNumber"),DocumentStatus=s?.Element(n+"WorkStatus")?.Value??string.Empty,WorkDate=Date(e,n+"WorkDate"),WorkType=Req(e,n+"WorkType"),SourceId=Req(e,n+"SourceID"),CustomerId=e.Element(n+"CustomerID")?.Value,SystemEntryDate=OptionalDateTime(e,n+"SystemEntryDate"),TaxPayable=Decimal(t,n+"TaxPayable"),NetTotal=Decimal(t,n+"NetTotal"),GrossTotal=Decimal(t,n+"GrossTotal")};foreach(var x in e.Elements(n+"Line")){var tax=x.Element(n+"Tax");r.Lines.Add(new(){LineNumber=Req(x,n+"LineNumber"),ProductCode=Req(x,n+"ProductCode"),ProductDescription=Req(x,n+"ProductDescription"),Quantity=Decimal(x,n+"Quantity"),UnitOfMeasure=Req(x,n+"UnitOfMeasure"),UnitPrice=Decimal(x,n+"UnitPrice"),TaxPointDate=OptionalDate(x,n+"TaxPointDate"),TaxType=tax?.Element(n+"TaxType")?.Value,TaxCode=tax?.Element(n+"TaxCode")?.Value,TaxPercentage=OptionalDecimal(tax,n+"TaxPercentage"),DebitAmount=OptionalDecimal(x,n+"DebitAmount")??0m,CreditAmount=OptionalDecimal(x,n+"CreditAmount")??0m});}return r;}
    private static SaftPaymentViewModel ParsePayment(XElement e){var n=e.Name.Namespace;var s=e.Element(n+"DocumentStatus");var t=e.Element(n+"DocumentTotals")??throw new InvalidDataException("O SAF-T (PT) contém um recibo sem DocumentTotals.");var r=new SaftPaymentViewModel{PaymentRefNo=Req(e,n+"PaymentRefNo"),TransactionDate=Date(e,n+"TransactionDate"),PaymentType=Req(e,n+"PaymentType"),Description=e.Element(n+"Description")?.Value,SourceId=Req(e,n+"SourceID"),CustomerId=e.Element(n+"CustomerID")?.Value,SystemEntryDate=OptionalDateTime(e,n+"SystemEntryDate"),PaymentStatus=s?.Element(n+"PaymentStatus")?.Value??string.Empty,TaxPayable=Decimal(t,n+"TaxPayable"),NetTotal=Decimal(t,n+"NetTotal"),GrossTotal=Decimal(t,n+"GrossTotal")};foreach(var x in e.Elements(n+"Line")){var source=x.Element(n+"SourceDocumentID");r.Lines.Add(new(){LineNumber=Req(x,n+"LineNumber"),OriginatingOn=source?.Element(n+"OriginatingON")?.Value,InvoiceDate=source is null?null:OptionalDate(source,n+"InvoiceDate"),Description=source?.Element(n+"Description")?.Value,DebitAmount=OptionalDecimal(source,n+"DebitAmount")??0m,CreditAmount=OptionalDecimal(source,n+"CreditAmount")??0m});}return r;}
    private static SaftTaxEntryViewModel ParseTaxEntry(XElement e){var n=e.Name.Namespace;return new(){TaxType=Req(e,n+"TaxType"),TaxCountryRegion=Req(e,n+"TaxCountryRegion"),TaxCode=Req(e,n+"TaxCode"),Description=Req(e,n+"Description"),TaxExpirationDate=OptionalDate(e,n+"TaxExpirationDate"),TaxPercentage=OptionalDecimal(e,n+"TaxPercentage"),TaxAmount=OptionalDecimal(e,n+"TaxAmount")};}
    private static SaftAccountViewModel ParseAccount(XElement e){var n=e.Name.Namespace;return new(){AccountId=Req(e,n+"AccountID"),Description=Req(e,n+"AccountDescription"),OpeningDebitBalance=Decimal(e,n+"OpeningDebitBalance"),OpeningCreditBalance=Decimal(e,n+"OpeningCreditBalance"),ClosingDebitBalance=Decimal(e,n+"ClosingDebitBalance"),ClosingCreditBalance=Decimal(e,n+"ClosingCreditBalance"),TaxonomyReference=e.Element(n+"TaxonomyReference")?.Value};}
    private static SaftPartyViewModel ParseParty(XElement e,string id,string tax){var n=e.Name.Namespace;return new(){PartyId=Req(e,n+id),AccountId=Req(e,n+"AccountID"),TaxId=Req(e,n+tax),CompanyName=Req(e,n+"CompanyName")};}
    private static SaftProductViewModel ParseProduct(XElement e){var n=e.Name.Namespace;return new(){ProductType=Req(e,n+"ProductType"),ProductCode=Req(e,n+"ProductCode"),ProductGroup=e.Element(n+"ProductGroup")?.Value,ProductDescription=Req(e,n+"ProductDescription"),ProductNumberCode=Req(e,n+"ProductNumberCode")};}
    private static string Opt(XElement p,XName n)=>p.Element(n)?.Value??string.Empty;private static string Req(XElement p,XName n){var v=p.Element(n)?.Value;if(string.IsNullOrWhiteSpace(v))throw new InvalidDataException($"O SAF-T (PT) contém um registo sem o campo obrigatório {n.LocalName}.");return v;}
    private static decimal Decimal(XElement p,XName n){if(!decimal.TryParse(Req(p,n),NumberStyles.Number,CultureInfo.InvariantCulture,out var v))throw new InvalidDataException($"O SAF-T (PT) contém um valor inválido em {n.LocalName}.");return v;}private static decimal? OptionalDecimal(XElement? p,XName n){var s=p?.Element(n)?.Value;if(string.IsNullOrWhiteSpace(s))return null;if(!decimal.TryParse(s,NumberStyles.Number,CultureInfo.InvariantCulture,out var v))throw new InvalidDataException($"O SAF-T (PT) contém um valor inválido em {n.LocalName}.");return v;}
    private static int Int(XElement p,XName n){if(!int.TryParse(Req(p,n),NumberStyles.Integer,CultureInfo.InvariantCulture,out var v))throw new InvalidDataException($"O SAF-T (PT) contém um valor inválido em {n.LocalName}.");return v;}private static DateOnly Date(XElement p,XName n){if(!DateOnly.TryParseExact(Req(p,n),"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var v))throw new InvalidDataException($"O SAF-T (PT) contém uma data inválida em {n.LocalName}.");return v;}private static DateOnly? OptionalDate(XElement p,XName n){var s=p.Element(n)?.Value;if(string.IsNullOrWhiteSpace(s))return null;if(!DateOnly.TryParseExact(s,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var v))throw new InvalidDataException($"O SAF-T (PT) contém uma data inválida em {n.LocalName}.");return v;}private static DateTime? OptionalDateTime(XElement p,XName n){var s=p.Element(n)?.Value;if(string.IsNullOrWhiteSpace(s))return null;if(!DateTime.TryParse(s,CultureInfo.InvariantCulture,DateTimeStyles.RoundtripKind,out var v))throw new InvalidDataException($"O SAF-T (PT) contém uma data/hora inválida em {n.LocalName}.");return v;}
    private static void ValidateRequiredHeader(SaftHeaderViewModel m){if(string.IsNullOrWhiteSpace(m.SaftVersion))throw new InvalidDataException("O cabeçalho SAF-T (PT) não contém o campo obrigatório AuditFileVersion.");if(string.IsNullOrWhiteSpace(m.CompanyName))throw new InvalidDataException("O cabeçalho SAF-T (PT) não contém o campo obrigatório CompanyName.");if(string.IsNullOrWhiteSpace(m.TaxRegistrationNumber))throw new InvalidDataException("O cabeçalho SAF-T (PT) não contém o campo obrigatório TaxRegistrationNumber.");}
}
