using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TabulariusAI.Web.Data;
#nullable disable
namespace TabulariusAI.Web.Migrations;
[DbContext(typeof(TabulariusDbContext))]
[Migration("20260831010000_AddSaftWorkingDocuments")]
public partial class AddSaftWorkingDocuments:Migration
{
 protected override void Up(MigrationBuilder m){m.CreateTable(name:"SaftWorkingDocuments",columns:t=>new{Id=t.Column<int>(nullable:false).Annotation("SqlServer:Identity","1, 1"),SaftImportId=t.Column<int>(nullable:false),DocumentNumber=t.Column<string>(maxLength:100,nullable:false),DocumentStatus=t.Column<string>(maxLength:10,nullable:false),WorkDate=t.Column<DateOnly>(nullable:false),WorkType=t.Column<string>(maxLength:10,nullable:false),SourceId=t.Column<string>(maxLength:100,nullable:false),CustomerId=t.Column<string>(maxLength:100,nullable:true),SystemEntryDate=t.Column<DateTime>(nullable:true),TaxPayable=t.Column<decimal>(type:"decimal(19,4)",nullable:false),NetTotal=t.Column<decimal>(type:"decimal(19,4)",nullable:false),GrossTotal=t.Column<decimal>(type:"decimal(19,4)",nullable:false)},constraints:t=>{t.PrimaryKey("PK_SaftWorkingDocuments",x=>x.Id);t.ForeignKey("FK_SaftWorkingDocuments_SaftImports_SaftImportId",x=>x.SaftImportId,"SaftImports","Id",onDelete:ReferentialAction.Cascade);});m.CreateTable(name:"SaftWorkingDocumentLines",columns:t=>new{Id=t.Column<int>(nullable:false).Annotation("SqlServer:Identity","1, 1"),SaftWorkingDocumentId=t.Column<int>(nullable:false),LineNumber=t.Column<string>(maxLength:100,nullable:false),ProductCode=t.Column<string>(maxLength:100,nullable:false),ProductDescription=t.Column<string>(maxLength:500,nullable:false),Quantity=t.Column<decimal>(type:"decimal(19,4)",nullable:false),UnitOfMeasure=t.Column<string>(maxLength:50,nullable:false),UnitPrice=t.Column<decimal>(type:"decimal(19,4)",nullable:false),TaxPointDate=t.Column<DateOnly>(nullable:true),TaxType=t.Column<string>(maxLength:20,nullable:true),TaxCode=t.Column<string>(maxLength:20,nullable:true),TaxPercentage=t.Column<decimal>(type:"decimal(9,4)",nullable:true),DebitAmount=t.Column<decimal>(type:"decimal(19,4)",nullable:false),CreditAmount=t.Column<decimal>(type:"decimal(19,4)",nullable:false)},constraints:t=>{t.PrimaryKey("PK_SaftWorkingDocumentLines",x=>x.Id);t.ForeignKey("FK_SaftWorkingDocumentLines_SaftWorkingDocuments_SaftWorkingDocumentId",x=>x.SaftWorkingDocumentId,"SaftWorkingDocuments","Id",onDelete:ReferentialAction.Cascade);});m.CreateIndex("IX_SaftWorkingDocuments_SaftImportId_DocumentNumber","SaftWorkingDocuments",new[]{"SaftImportId","DocumentNumber"},unique:true);m.CreateIndex("IX_SaftWorkingDocuments_SaftImportId_WorkDate","SaftWorkingDocuments",new[]{"SaftImportId","WorkDate"});m.CreateIndex("IX_SaftWorkingDocumentLines_SaftWorkingDocumentId_LineNumber","SaftWorkingDocumentLines",new[]{"SaftWorkingDocumentId","LineNumber"},unique:true);}
 protected override void Down(MigrationBuilder m){m.DropTable("SaftWorkingDocumentLines");m.DropTable("SaftWorkingDocuments");}
}
