using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TabulariusAI.Web.Data;

#nullable disable

namespace TabulariusAI.Web.Migrations;

/// <summary>Represents the Entity Framework Core model snapshot for the local Tabularius database.</summary>
[DbContext(typeof(TabulariusDbContext))]
public partial class TabulariusDbContextModelSnapshot : ModelSnapshot
{
    /// <inheritdoc />
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "9.0.0").HasAnnotation("Relational:MaxIdentifierLength", 128);
        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b => { b.Property<string>("Id").HasColumnType("nvarchar(450)"); b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)"); b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)"); b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)"); b.HasKey("Id"); b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL"); b.ToTable("AspNetRoles", (string)null); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("ClaimType").HasColumnType("nvarchar(max)"); b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)"); b.Property<string>("RoleId").IsRequired().HasColumnType("nvarchar(450)"); b.HasKey("Id"); b.HasIndex("RoleId"); b.ToTable("AspNetRoleClaims", (string)null); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("ClaimType").HasColumnType("nvarchar(max)"); b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)"); b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)"); b.HasKey("Id"); b.HasIndex("UserId"); b.ToTable("AspNetUserClaims", (string)null); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b => { b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)"); b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)"); b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)"); b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)"); b.HasKey("LoginProvider", "ProviderKey"); b.HasIndex("UserId"); b.ToTable("AspNetUserLogins", (string)null); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b => { b.Property<string>("UserId").HasColumnType("nvarchar(450)"); b.Property<string>("RoleId").HasColumnType("nvarchar(450)"); b.HasKey("UserId", "RoleId"); b.HasIndex("RoleId"); b.ToTable("AspNetUserRoles", (string)null); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b => { b.Property<string>("UserId").HasColumnType("nvarchar(450)"); b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)"); b.Property<string>("Name").HasColumnType("nvarchar(450)"); b.Property<string>("Value").HasColumnType("nvarchar(max)"); b.HasKey("UserId", "LoginProvider", "Name"); b.ToTable("AspNetUserTokens", (string)null); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Identity.ApplicationUser", b => { b.Property<string>("Id").HasColumnType("nvarchar(450)"); b.Property<int>("AccessFailedCount").HasColumnType("int"); b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)"); b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetimeoffset"); b.Property<string>("DisplayName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)"); b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)"); b.Property<bool>("EmailConfirmed").HasColumnType("bit"); b.Property<bool>("LockoutEnabled").HasColumnType("bit"); b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset"); b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)"); b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)"); b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)"); b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)"); b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit"); b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)"); b.Property<bool>("TwoFactorEnabled").HasColumnType("bit"); b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)"); b.HasKey("Id"); b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex"); b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL"); b.ToTable("AspNetUsers", (string)null); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.AccountingEntity", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2"); b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)"); b.Property<string>("TaxRegistrationNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)"); b.HasKey("Id"); b.HasIndex("TaxRegistrationNumber").IsUnique(); b.ToTable("AccountingEntities"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.AnalysisDossier", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<int>("AccountingEntityId").HasColumnType("int"); b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2"); b.Property<int>("FiscalYear").HasColumnType("int"); b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)"); b.HasKey("Id"); b.HasIndex("AccountingEntityId", "FiscalYear").IsUnique(); b.ToTable("AnalysisDossiers"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftImport", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("ContentHash").IsFixedLength().HasMaxLength(64).HasColumnType("nchar(64)"); b.Property<int>("DossierId").HasColumnType("int"); b.Property<DateOnly?>("EndDate").HasColumnType("date"); b.Property<DateTime>("ImportedAtUtc").HasColumnType("datetime2"); b.Property<string>("OriginalFileName").IsRequired().HasMaxLength(260).HasColumnType("nvarchar(260)"); b.Property<string>("SaftVersion").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)"); b.Property<DateOnly?>("StartDate").HasColumnType("date"); b.HasKey("Id"); b.HasIndex("ContentHash").IsUnique().HasFilter("[ContentHash] IS NOT NULL"); b.HasIndex("DossierId"); b.ToTable("SaftImports"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftAccount", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("AccountId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<decimal>("ClosingCreditBalance").HasPrecision(19, 4).HasColumnType("decimal(19,4)"); b.Property<decimal>("ClosingDebitBalance").HasPrecision(19, 4).HasColumnType("decimal(19,4)"); b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)"); b.Property<decimal>("OpeningCreditBalance").HasPrecision(19, 4).HasColumnType("decimal(19,4)"); b.Property<decimal>("OpeningDebitBalance").HasPrecision(19, 4).HasColumnType("decimal(19,4)"); b.Property<int>("SaftImportId").HasColumnType("int"); b.Property<string>("TaxonomyReference").HasMaxLength(100).HasColumnType("nvarchar(100)"); b.HasKey("Id"); b.HasIndex("SaftImportId", "AccountId").IsUnique(); b.ToTable("SaftAccounts"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftCustomer", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("AccountId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("CompanyName").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)"); b.Property<string>("CustomerId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<int>("SaftImportId").HasColumnType("int"); b.Property<string>("TaxId").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)"); b.HasKey("Id"); b.HasIndex("SaftImportId", "CustomerId").IsUnique(); b.ToTable("SaftCustomers"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftSupplier", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("AccountId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("CompanyName").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)"); b.Property<int>("SaftImportId").HasColumnType("int"); b.Property<string>("SupplierId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("TaxId").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)"); b.HasKey("Id"); b.HasIndex("SaftImportId", "SupplierId").IsUnique(); b.ToTable("SaftSuppliers"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftProduct", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("ProductCode").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("ProductDescription").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)"); b.Property<string>("ProductGroup").HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("ProductNumberCode").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("ProductType").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)"); b.Property<int>("SaftImportId").HasColumnType("int"); b.HasKey("Id"); b.HasIndex("SaftImportId", "ProductCode").IsUnique(); b.ToTable("SaftProducts"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftTransaction", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("CustomerId").HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)"); b.Property<string>("DocArchivalNumber").HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<DateOnly>("GlPostingDate").HasColumnType("date"); b.Property<string>("JournalDescription").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)"); b.Property<string>("JournalId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<int>("Period").HasColumnType("int"); b.Property<int>("SaftImportId").HasColumnType("int"); b.Property<string>("SourceId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("SupplierId").HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<DateOnly>("TransactionDate").HasColumnType("date"); b.Property<string>("TransactionId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<string>("TransactionType").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)"); b.HasKey("Id"); b.HasIndex("SaftImportId", "JournalId"); b.HasIndex("SaftImportId", "TransactionDate"); b.HasIndex("SaftImportId", "TransactionId").IsUnique(); b.ToTable("SaftTransactions"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftTransactionLine", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); b.Property<string>("AccountId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<decimal>("Amount").HasPrecision(19, 4).HasColumnType("decimal(19,4)"); b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)"); b.Property<string>("RecordId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<int>("SaftTransactionId").HasColumnType("int"); b.Property<string>("Side").IsRequired().IsFixedLength().HasMaxLength(1).HasColumnType("nchar(1)"); b.Property<string>("SourceDocumentId").HasMaxLength(100).HasColumnType("nvarchar(100)"); b.Property<DateTime?>("SystemEntryDate").HasColumnType("datetime2"); b.HasKey("Id"); b.HasIndex("AccountId"); b.HasIndex("SaftTransactionId", "RecordId").IsUnique(); b.ToTable("SaftTransactionLines"); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b => { b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b => { b.HasOne("TabulariusAI.Web.Data.Identity.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b => { b.HasOne("TabulariusAI.Web.Data.Identity.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b => { b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.HasOne("TabulariusAI.Web.Data.Identity.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b => { b.HasOne("TabulariusAI.Web.Data.Identity.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.AnalysisDossier", b => { b.HasOne("TabulariusAI.Web.Data.Entities.AccountingEntity", "AccountingEntity").WithMany("Dossiers").HasForeignKey("AccountingEntityId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("AccountingEntity"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftImport", b => { b.HasOne("TabulariusAI.Web.Data.Entities.AnalysisDossier", "Dossier").WithMany("Imports").HasForeignKey("DossierId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("Dossier"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftAccount", b => { b.HasOne("TabulariusAI.Web.Data.Entities.SaftImport", "SaftImport").WithMany("Accounts").HasForeignKey("SaftImportId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("SaftImport"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftCustomer", b => { b.HasOne("TabulariusAI.Web.Data.Entities.SaftImport", "SaftImport").WithMany("Customers").HasForeignKey("SaftImportId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("SaftImport"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftSupplier", b => { b.HasOne("TabulariusAI.Web.Data.Entities.SaftImport", "SaftImport").WithMany("Suppliers").HasForeignKey("SaftImportId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("SaftImport"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftProduct", b => { b.HasOne("TabulariusAI.Web.Data.Entities.SaftImport", "SaftImport").WithMany("Products").HasForeignKey("SaftImportId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("SaftImport"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftTransaction", b => { b.HasOne("TabulariusAI.Web.Data.Entities.SaftImport", "SaftImport").WithMany("Transactions").HasForeignKey("SaftImportId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("SaftImport"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftTransactionLine", b => { b.HasOne("TabulariusAI.Web.Data.Entities.SaftTransaction", "SaftTransaction").WithMany("Lines").HasForeignKey("SaftTransactionId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("SaftTransaction"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.AccountingEntity", b => b.Navigation("Dossiers"));
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.AnalysisDossier", b => b.Navigation("Imports"));
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftImport", b => { b.Navigation("Accounts"); b.Navigation("Customers"); b.Navigation("Products"); b.Navigation("Suppliers"); b.Navigation("Transactions"); });
        modelBuilder.Entity("TabulariusAI.Web.Data.Entities.SaftTransaction", b => b.Navigation("Lines"));
    }
}
