using System.Text;
using TabulariusAI.Web.Models;
using TabulariusAI.Web.Services;
using Xunit;

namespace TabulariusAI.Web.Tests.Services;

/// <summary>Verifies SAF-T (PT) parsing and validation boundaries.</summary>
public sealed class SaftHeaderReaderTests
{
    /// <summary>Verifies complete supported master data, ledger and sales parsing.</summary>
    [Fact] public async Task ReadAsync_ValidSaft_ReturnsMasterDataDocumentsAndStructuralCounts(){const string xml="""
<?xml version="1.0" encoding="utf-8"?><AuditFile xmlns="urn:OECD:StandardAuditFile-Tax:PT_1.04_01"><Header><AuditFileVersion>1.04_01</AuditFileVersion><TaxRegistrationNumber>999999990</TaxRegistrationNumber><CompanyName>Empresa Teste</CompanyName><FiscalYear>2026</FiscalYear></Header><MasterFiles><GeneralLedgerAccounts><Account><AccountID>11</AccountID><AccountDescription>Caixa</AccountDescription><OpeningDebitBalance>10</OpeningDebitBalance><OpeningCreditBalance>0</OpeningCreditBalance><ClosingDebitBalance>20</ClosingDebitBalance><ClosingCreditBalance>0</ClosingCreditBalance><TaxonomyReference>1</TaxonomyReference></Account></GeneralLedgerAccounts><Customer><CustomerID>C1</CustomerID><AccountID>2111</AccountID><CustomerTaxID>500000001</CustomerTaxID><CompanyName>Cliente</CompanyName></Customer><Supplier><SupplierID>S1</SupplierID><AccountID>2211</AccountID><SupplierTaxID>500000002</SupplierTaxID><CompanyName>Fornecedor</CompanyName></Supplier><Product><ProductType>P</ProductType><ProductCode>P1</ProductCode><ProductGroup>Mercadorias</ProductGroup><ProductDescription>Produto</ProductDescription><ProductNumberCode>5600000000011</ProductNumberCode></Product></MasterFiles><GeneralLedgerEntries><Journal><JournalID>VEN</JournalID><Description>Vendas</Description><Transaction><TransactionID>T1</TransactionID><Period>3</Period><TransactionDate>2026-03-15</TransactionDate><SourceID>TEST</SourceID><Description>Venda</Description><TransactionType>N</TransactionType><GLPostingDate>2026-03-15</GLPostingDate><Lines><DebitLine><RecordID>1</RecordID><AccountID>2111</AccountID><Description>Cliente</Description><DebitAmount>123</DebitAmount></DebitLine><CreditLine><RecordID>2</RecordID><AccountID>71</AccountID><Description>Venda</Description><CreditAmount>123</CreditAmount></CreditLine></Lines></Transaction></Journal></GeneralLedgerEntries><SourceDocuments><SalesInvoices><Invoice><InvoiceNo>FT 1/1</InvoiceNo><InvoiceDate>2026-03-15</InvoiceDate><InvoiceType>FT</InvoiceType><SourceID>TEST</SourceID><Line><LineNumber>1</LineNumber><ProductCode>P1</ProductCode><ProductDescription>Produto</ProductDescription><Quantity>1</Quantity><UnitOfMeasure>UN</UnitOfMeasure><UnitPrice>100</UnitPrice><TaxPointDate>2026-03-15</TaxPointDate><CreditAmount>100</CreditAmount><Tax><TaxPercentage>23</TaxPercentage></Tax></Line><DocumentTotals><TaxPayable>23</TaxPayable><NetTotal>100</NetTotal><GrossTotal>123</GrossTotal></DocumentTotals></Invoice></SalesInvoices><MovementOfGoods><StockMovement /></MovementOfGoods><WorkingDocuments><WorkDocument /></WorkingDocuments><Payments><Payment /></Payments></SourceDocuments></AuditFile>
""";var r=await ReadAsync(xml);Assert.Single(r.Accounts);Assert.Equal("1",r.Accounts[0].TaxonomyReference);Assert.Single(r.Customers);Assert.Single(r.Suppliers);Assert.Single(r.Products);Assert.Single(r.Transactions);Assert.Equal(123m,r.Transactions[0].TotalDebit);Assert.Equal(123m,r.Transactions[0].TotalCredit);Assert.Equal(23m,Assert.Single(Assert.Single(r.SalesInvoices).Lines).TaxPercentage);Assert.Equal(1,r.MovementOfGoodsCount);Assert.Equal(1,r.WorkingDocumentCount);Assert.Equal(1,r.PaymentCount);}
    /// <summary>Verifies debit invoice lines and absent optional values.</summary>
    [Fact] public async Task ReadAsync_InvoiceDebitLineAndOptionalFields_MapsValues(){var r=await ReadAsync(Wrap("<SourceDocuments><SalesInvoices><Invoice><InvoiceNo>NC 1/1</InvoiceNo><InvoiceDate>2026-01-10</InvoiceDate><InvoiceType>NC</InvoiceType><SourceID>U</SourceID><Line><LineNumber>1</LineNumber><ProductCode>P1</ProductCode><ProductDescription>Nota</ProductDescription><Quantity>2.5</Quantity><UnitOfMeasure>UN</UnitOfMeasure><UnitPrice>10.4</UnitPrice><DebitAmount>26</DebitAmount></Line><DocumentTotals><TaxPayable>0</TaxPayable><NetTotal>26</NetTotal><GrossTotal>26</GrossTotal></DocumentTotals></Invoice></SalesInvoices></SourceDocuments>"));var line=Assert.Single(Assert.Single(r.SalesInvoices).Lines);Assert.Equal(26m,line.DebitAmount);Assert.Equal(0m,line.CreditAmount);Assert.Null(line.TaxPointDate);Assert.Null(line.TaxPercentage);}
    /// <summary>Verifies null streams are rejected.</summary>
    [Fact] public async Task ReadAsync_NullStream_Throws()=>await Assert.ThrowsAsync<ArgumentNullException>(()=>new SaftHeaderReader().ReadAsync(null!));
    /// <summary>Verifies non-SAF-T XML is rejected.</summary>
    [Fact] public async Task ReadAsync_NonSaftXml_ThrowsInvalidDataException()=>await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync("<Document />"));
    /// <summary>Verifies invalid namespaces are rejected.</summary>
    [Fact] public async Task ReadAsync_InvalidNamespace_Throws()=>await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync("<AuditFile><Header /></AuditFile>"));
    /// <summary>Verifies DTD processing is prohibited.</summary>
    [Fact] public async Task ReadAsync_DocumentTypeDeclaration_ThrowsInvalidDataException()=>await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync("<!DOCTYPE AuditFile [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]><AuditFile>&xxe;</AuditFile>"));
    /// <summary>Verifies malformed XML is normalized to an invalid-data exception.</summary>
    [Fact] public async Task ReadAsync_MalformedXml_ThrowsInvalidDataException(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync("<AuditFile xmlns='urn:OECD:StandardAuditFile-Tax:PT_1.04_01'><Header>"));Assert.Contains("XML SAF-T (PT)",e.Message);}
    /// <summary>Verifies required header fields are enforced.</summary>
    [Theory][InlineData("AuditFileVersion","1.04_01")][InlineData("CompanyName","Test Company")][InlineData("TaxRegistrationNumber","999999990")] public async Task ReadAsync_MissingRequiredHeaderField_Throws(string field,string value){var header=Header().Replace($"<{field}>{value}</{field}>",string.Empty,StringComparison.Ordinal);var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap(string.Empty,header)));Assert.Contains(field,e.Message);}
    /// <summary>Verifies missing required record values are rejected.</summary>
    [Fact] public async Task ReadAsync_AccountMissingDescription_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap("<MasterFiles><GeneralLedgerAccounts><Account><AccountID>11</AccountID><OpeningDebitBalance>0</OpeningDebitBalance><OpeningCreditBalance>0</OpeningCreditBalance><ClosingDebitBalance>0</ClosingDebitBalance><ClosingCreditBalance>0</ClosingCreditBalance></Account></GeneralLedgerAccounts></MasterFiles>")));Assert.Contains("AccountDescription",e.Message);}
    /// <summary>Verifies invalid decimals are rejected.</summary>
    [Fact] public async Task ReadAsync_InvalidDecimal_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap("<MasterFiles><GeneralLedgerAccounts><Account><AccountID>11</AccountID><AccountDescription>Cash</AccountDescription><OpeningDebitBalance>abc</OpeningDebitBalance><OpeningCreditBalance>0</OpeningCreditBalance><ClosingDebitBalance>0</ClosingDebitBalance><ClosingCreditBalance>0</ClosingCreditBalance></Account></GeneralLedgerAccounts></MasterFiles>")));Assert.Contains("OpeningDebitBalance",e.Message);}
    /// <summary>Verifies invalid integer periods are rejected.</summary>
    [Fact] public async Task ReadAsync_InvalidPeriod_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap(Transaction("x","2026-01-01",true))));Assert.Contains("Period",e.Message);}
    /// <summary>Verifies invalid required dates are rejected.</summary>
    [Fact] public async Task ReadAsync_InvalidTransactionDate_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap(Transaction("1","01/01/2026",true))));Assert.Contains("TransactionDate",e.Message);}
    /// <summary>Verifies transactions require Lines.</summary>
    [Fact] public async Task ReadAsync_TransactionWithoutLines_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap(Transaction("1","2026-01-01",false))));Assert.Contains("Lines",e.Message);}
    /// <summary>Verifies invoices require document totals.</summary>
    [Fact] public async Task ReadAsync_InvoiceWithoutTotals_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap("<SourceDocuments><SalesInvoices><Invoice><InvoiceNo>FT 1/1</InvoiceNo><InvoiceDate>2026-01-01</InvoiceDate><InvoiceType>FT</InvoiceType><SourceID>U</SourceID></Invoice></SalesInvoices></SourceDocuments>")));Assert.Contains("DocumentTotals",e.Message);}
    /// <summary>Verifies invalid optional dates are rejected.</summary>
    [Fact] public async Task ReadAsync_InvalidOptionalTaxPointDate_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap(InvoiceLine("<TaxPointDate>bad</TaxPointDate>"))));Assert.Contains("TaxPointDate",e.Message);}
    /// <summary>Verifies invalid optional date-times are rejected.</summary>
    [Fact] public async Task ReadAsync_InvalidOptionalSystemEntryDate_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap("<SourceDocuments><SalesInvoices><Invoice><InvoiceNo>FT 1</InvoiceNo><InvoiceDate>2026-01-01</InvoiceDate><InvoiceType>FT</InvoiceType><SourceID>U</SourceID><SystemEntryDate>bad</SystemEntryDate><DocumentTotals><TaxPayable>0</TaxPayable><NetTotal>0</NetTotal><GrossTotal>0</GrossTotal></DocumentTotals></Invoice></SalesInvoices></SourceDocuments>")));Assert.Contains("SystemEntryDate",e.Message);}
    /// <summary>Verifies invalid optional decimals are rejected.</summary>
    [Fact] public async Task ReadAsync_InvalidOptionalTaxPercentage_Throws(){var e=await Assert.ThrowsAsync<InvalidDataException>(()=>ReadAsync(Wrap(InvoiceLine("<Tax><TaxPercentage>abc</TaxPercentage></Tax>"))));Assert.Contains("TaxPercentage",e.Message);}

    /// <summary>Reads a UTF-8 SAF-T test document.</summary>
    private static async Task<SaftHeaderViewModel> ReadAsync(string xml){await using var s=new MemoryStream(Encoding.UTF8.GetBytes(xml));return await new SaftHeaderReader().ReadAsync(s);}
    /// <summary>Wraps content in a minimal valid SAF-T document.</summary>
    private static string Wrap(string body,string? header=null)=>$"<AuditFile xmlns=\"urn:OECD:StandardAuditFile-Tax:PT_1.04_01\">{header??Header()}{body}</AuditFile>";
    /// <summary>Returns a minimal valid header.</summary>
    private static string Header()=>"<Header><AuditFileVersion>1.04_01</AuditFileVersion><TaxRegistrationNumber>999999990</TaxRegistrationNumber><CompanyName>Test Company</CompanyName><FiscalYear>2026</FiscalYear></Header>";
    /// <summary>Creates a transaction fragment.</summary>
    private static string Transaction(string period,string date,bool lines)=>$"<GeneralLedgerEntries><Journal><JournalID>GJ</JournalID><Description>General</Description><Transaction><TransactionID>T1</TransactionID><Period>{period}</Period><TransactionDate>{date}</TransactionDate><SourceID>U</SourceID><Description>Test</Description><TransactionType>N</TransactionType><GLPostingDate>2026-01-01</GLPostingDate>{(lines?"<Lines />":string.Empty)}</Transaction></Journal></GeneralLedgerEntries>";
    /// <summary>Creates an invoice containing one configurable line.</summary>
    private static string InvoiceLine(string optional)=>$"<SourceDocuments><SalesInvoices><Invoice><InvoiceNo>FT 1</InvoiceNo><InvoiceDate>2026-01-01</InvoiceDate><InvoiceType>FT</InvoiceType><SourceID>U</SourceID><Line><LineNumber>1</LineNumber><ProductCode>P1</ProductCode><ProductDescription>P</ProductDescription><Quantity>1</Quantity><UnitOfMeasure>UN</UnitOfMeasure><UnitPrice>1</UnitPrice>{optional}<CreditAmount>1</CreditAmount></Line><DocumentTotals><TaxPayable>0</TaxPayable><NetTotal>1</NetTotal><GrossTotal>1</GrossTotal></DocumentTotals></Invoice></SalesInvoices></SourceDocuments>";
}
